var actions = {
	"first":[
		{
			"slide":0,
			"transitions":[]
		}
	],
	"introduction":[
		{
			"slide":0,
			"transitions":[
				{
					"selectedItem":"*[data-ix='next-btn-load']",
					"addedClass":"animate"					
				}
			]
		},
		{
			"slide":1,
			"transitions":[
				{
					"selectedItem":".div-score-bottom",
					"addedClass":"popup"					
				}
			]
		},
		{
			"slide":2,
			"transitions":[]
		}
	],
	"scenario1":[
		{
			"slide":0,
			"transitions":[
				{
					"selectedItem":"*[data-ix='next-btn-load']",
					"addedClass":"animate"					
				},
				{
					"selectedItem":".div-dimmer.intro",
					"addedClass":"dim"					
				},
				{
					"selectedItem":".div-scenario-background",
					"addedClass":"popup"					
				},
				{
					"selectedItem":".img-2up-right.building",
					"addedClass":"popup"					
				},
				{
					"selectedItem":".img-2up-left.car",
					"addedClass":"popup"					
				}
			]
		},
		{
			"slide":1,
			"transitions":[]
		},
		{
			"slide":2,
			"transitions":[]
		},
		{
			"slide":3,
			"transitions":[
				{
					"selectedItem":".img-2up-right.building",
					"addedClass":"popup"					
				},
				{
					"selectedItem":".img-2up-left.car",
					"addedClass":"popup"					
				}
			]
		}
	],
	"decision1":[
		{
			"slide":0,
			"transitions":[
				{
					"selectedItem":".div-decision-button.choice-1",
					"addedClass":"appear"					
				},{
					"selectedItem":".div-decision-button.choice-2",
					"addedClass":"appear"					
				}]
		}
	],
	"outcome1a":[
		{
			"slide":0,
			"transitions":[
				{
					"selectedItem":"*[data-ix='next-btn-load']",
					"addedClass":"animate"					
				},
				{
					"selectedItem":".div-score-bottom",
					"addedClass":"highlight"					
				},
				{
					"selectedItem":".image-bullet-sprite.empty",
					"addedClass":"pulse"
				},
				{
					"selectedItem":".img-2up-left",
					"addedClass":"popup"
				},
				{
					"selectedItem":".img-2up-right",
					"addedClass":"popup"
				}				
			]
		},
		{
			"slide":1,
			"transitions":[]
		},
		{
			"slide":2,
			"transitions":[]
		},
		{
			"slide":3,
			"transitions":[]
		},
		{
			"slide":4,
			"transitions":[]
		}
	],
	"outcome1b":[
		{
			"slide":0,
			"transitions":[
				{
					"selectedItem":"*[data-ix='next-btn-load']",
					"addedClass":"animate"					
				},
				{
					"selectedItem":".div-score-bottom",
					"addedClass":"highlight"					
				},
				{
					"selectedItem":".image-bullet-sprite.empty",
					"addedClass":"pulse"
				},
				{
					"selectedItem":".img-2up-left",
					"addedClass":"popup"
				},
				{
					"selectedItem":".img-2up-right",
					"addedClass":"popup"
				}				
			]
		},
		{
			"slide":1,
			"transitions":[]
		},
		{
			"slide":2,
			"transitions":[]
		},
		{
			"slide":3,
			"transitions":[]
		},
		{
			"slide":4,
			"transitions":[]
		}
	],
	"scenario2":[
		{
			"slide":0,
			"transitions":[
				{
					"selectedItem":"*[data-ix='next-btn-load']",
					"addedClass":"animate"					
				},
				{
					"selectedItem":".div-dimmer.intro",
					"addedClass":"dim"					
				},
				{
					"selectedItem":".div-scenario-background",
					"addedClass":"popup"					
				},
				{
					"selectedItem":".img-2up-right.building",
					"addedClass":"popup"					
				},
				{
					"selectedItem":".img-2up-left.car",
					"addedClass":"popup"					
				}
			]
		},
		{
			"slide":1,
			"transitions":[]
		},
		{
			"slide":2,
			"transitions":[]
		},
		{
			"slide":3,
			"transitions":[
				{
					"selectedItem":".img-2up-right.building",
					"addedClass":"popup"					
				},
				{
					"selectedItem":".img-2up-left.car",
					"addedClass":"popup"					
				}
			]
		}
	],
	"decision2":[
		{
			"slide":0,
			"transitions":[
				{
					"selectedItem":".div-decision-button.choice-1",
					"addedClass":"appear"					
				},{
					"selectedItem":".div-decision-button.choice-2",
					"addedClass":"appear"					
				},{
					"selectedItem":".div-decision-button.choice-3",
					"addedClass":"appear"					
				}
			]
		}
	],
	"outcome2a":[
		{
			"slide":0,
			"transitions":[]
		}
	],
	"outcome2b":[
		{
			"slide":0,
			"transitions":[]
		}
	],
	"outcome2c":[
		{
			"slide":0,
			"transitions":[]
		}
	],
	"scenario3":[
		{
			"slide":0,
			"transitions":[]
		}
	],
	"decision3":[
		{
			"slide":0,
			"transitions":[]
		}
	],
	"outcome3a":[
		{
			"slide":0,
			"transitions":[]
		}
	],
	"outcome3b":[
		{
			"slide":0,
			"transitions":[]
		}
	],
	"conclusion":[
		{
			"slide":0,
			"transitions":[]
		}
	]
}